// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CardElementTest01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cardElementTest01() {
    // Test name: CardElementTest01
    // Step # | name | target | value
    // 1 | open | https://my.accountable2you.dev/Signup/Payment?planId=25 | 
    driver.get("https://my.accountable2you.dev/Signup/Payment?planId=25");
    // 2 | setWindowSize | 1392x1123 | 
    driver.manage().window().setSize(new Dimension(1392, 1123));
    // 3 | selectFrame | index=1 | 
    driver.switchTo().frame(1);
    // 4 | click | name=cardnumber | 
    driver.findElement(By.name("cardnumber")).click();
    // 5 | type | name=cardnumber | 4242 4242 4242 4242
    driver.findElement(By.name("cardnumber")).sendKeys("4242 4242 4242 4242");
    // 6 | type | name=exp-date | 04 / 24
    driver.findElement(By.name("exp-date")).sendKeys("04 / 24");
    // 7 | type | name=cvc | 242
    driver.findElement(By.name("cvc")).sendKeys("242");
    // 8 | type | name=postal | 42424
    driver.findElement(By.name("postal")).sendKeys("42424");
    // 9 | click | css=.container-centered-wrapper | 
    driver.findElement(By.cssSelector(".container-centered-wrapper")).click();
  }
}
