// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignupTest23072501Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signupTest23072501() {
    // Test name: Signup Test 23072501
    // Step # | name | target | value
    // 1 | open | /Account/Login | 
    driver.get("https://my.accountable2you.dev/Account/Login");
    // 2 | setWindowSize | 1392x1123 | 
    driver.manage().window().setSize(new Dimension(1392, 1123));
    // 3 | click | linkText=Sign up | 
    driver.findElement(By.linkText("Sign up")).click();
    // 4 | click | linkText=Sign Up Today! | 
    driver.findElement(By.linkText("Sign Up Today!")).click();
    // 7 | click | id=FirstName | 
    driver.findElement(By.id("FirstName")).click();
    // 8 | type | id=FirstName | atest23072501
    driver.findElement(By.id("FirstName")).sendKeys("atest23072501");
    // 9 | type | id=LastName | last
    driver.findElement(By.id("LastName")).sendKeys("last");
    // 10 | type | id=Email | aiden.a2ydev+23072501@gmail.com
    driver.findElement(By.id("Email")).sendKeys("aiden.a2ydev+23072501@gmail.com");
    // 11 | type | id=username | atest23072501
    driver.findElement(By.id("username")).sendKeys("atest23072501");
    // 12 | type | id=password | password
    driver.findElement(By.id("password")).sendKeys("password");
    // 13 | type | id=ConfirmPassword | password
    driver.findElement(By.id("ConfirmPassword")).sendKeys("password");
    // 14 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 15 | click | css=.text-uppercase | 
    driver.findElement(By.cssSelector(".text-uppercase")).click();
    // 16 | click | css=.btn-success | 
    driver.findElement(By.cssSelector(".btn-success")).click();
    // 17 | selectFrame | index=1 | 
    driver.switchTo().frame(1);
    // 18 | click | name=cardnumber | 
    driver.findElement(By.name("cardnumber")).click();
    // 19 | type | name=cardnumber | 4242 4242 4242 4242
    driver.findElement(By.name("cardnumber")).sendKeys("4242 4242 4242 4242");
    // 20 | type | name=exp-date | 04 / 24
    driver.findElement(By.name("exp-date")).sendKeys("04 / 24");
    // 21 | type | name=cvc | 242
    driver.findElement(By.name("cvc")).sendKeys("242");
    // 22 | type | name=postal | 42424
    driver.findElement(By.name("postal")).sendKeys("42424");
    // 23 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 24 | click | css=.container-centered-wrapper | 
    driver.findElement(By.cssSelector(".container-centered-wrapper")).click();
  }
}
